export var myNotes = [{
  id: 1,
  notesHeading: "Heading1",
  desc: "blabla"
}, {
  id: 2,
  notesHeading: "Heading2",
  desc: "blabla2"
}, {
  id: 3,
  notesHeading: "Heading3",
  desc: "blabla3"
}, {
  id: 4,
  notesHeading: "Heading4",
  desc: "blabla4"
}, {
  id: 5,
  notesHeading: "Heading5",
  desc: "blabla5"
}, {
  id: 6,
  notesHeading: "Heading6",
  desc: "blabla6"
}, {
  id: 7,
  notesHeading: "Heading7",
  desc: "blabla7"
}, {
  id: 8,
  notesHeading: "Heading8",
  desc: "blabla8"
}, {
  id: 9,
  notesHeading: "Heading9",
  desc: "blabla9"
}, {
  id: 10,
  notesHeading: "Heading10",
  desc: "blabla10"
}]
